[tools]
# =================================================================================================
# Project Tools
# =================================================================================================
go = "1.25.5"
"aqua:golangci/golangci-lint" = "2.8.0"
"aqua:goreleaser/goreleaser" = "2.13.3"
"aqua:siderolabs/talos" = "1.12.1"

# =================================================================================================
# Misc Tools
# =================================================================================================
"direnv" = "latest"

# =================================================================================================
# CI Tools
# =================================================================================================
"aqua:rhysd/actionlint" = "1"
"shellcheck" = "0.11"
svu = "latest"

# =================================================================================================
# TASKS
# =================================================================================================
[tasks."release"]
description = "Run goreleaser in snapshot mode."
run = "goreleaser release --snapshot --clean"

[tasks."lint"]
description = "Run golangci-lint in fix mode."
run = "golangci-lint run --fix"

[tasks."test"]
description = "Run e2e tests."
run = "bash scripts/test.sh"
